### ISSUE TITLE
Python Visualization

### ISSUE THREAD

**Issue by knbarton** [knbarton/ners570-finalproject#11]
This issue is complete when there is a working Python script which creates an animated visualization of the output data from the Fortran model.

**Comment by littlewatkins** [comment]
I added a plot_tsunami.py that is a copy of the plot.py with a few minor modifications. It creates a png for the cmake build, so I am closing this issue for now.

**Comment by knbarton** [comment]
I'm going to reopen this issue because my goal was to have an animated visual at the end, so I'm going to work on this some more. Also, I assume this means plot.py is redundant now, so I should be able to delete that one right?

**Comment by littlewatkins** [comment]
Sounds good!

And yes it's redundant now. I didn't remove it because I wasn't sure about why you add certain parts like `<<<<<<<Head` and `>>>>>>>main` in it, so I was going to ask you about that.

**Comment by knbarton** [comment]
I put in a pull request for the animation, and I included some file cleanup. One issue though is that I can't seem to call the python script using travis.yml because it can't import the matplotlib module. I'm not sure why this is happening since I don't think it had any trouble before. For now, I've just removed that line from .travis.yml so that it's not being called.

**Comment by littlewatkins** [comment]
I fixed the .travis.yml file so that it installs the matplotlib, pandas, and imageio packages into the environment, and has it run the plot script. I figured that was the problem because I had that within my own environment. I'll merge the pull request since that's working now.
