### ISSUE TITLE
Make basic working model

### ISSUE THREAD

**Issue by knbarton** [knbarton/ners570-finalproject#7]
This issue is complete when we have a basic working tidal model in Fortran. This issue does not require the parallelism or the python visualization code to be complete.

**Comment by knbarton** [comment]
The code for the basic working model is in branch `basic_model_7`.  It compiled and ran when I did it by hand, but it doesn't seem to be working quite yet with the Travis CI system. Once I get that sorted, I'll do a pull request.

Also, the modules are probably not necessary since all the subroutines they contain could be defined in the main script instead. We could change this, but I think it's nice to have things separated out into modules just to get some practice with them.

**Comment by littlewatkins** [comment]
Having modules and subroutines would be good for testing, so I agree that having things be separated is good.
